name: CI/CD → ALPB production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Check out the repo
      - uses: actions/checkout@v4

      # 2️⃣ Trust the host key (first-connect prompt killer)
      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      # 3️⃣ Deploy
      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host:     ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key:      ${{ secrets.SSH_KEY }}          # ← NEW (raw private key from Secrets)

          script: |
            set -e
            cd alpb-website

            pm2 delete alpb-frontend || true
            pm2 delete alpb-backend  || true

            git pull origin main

            # ── Frontend ────────────────────────────────
            cd frontend
            nvm use 22 || . $NVM_DIR/nvm.sh && nvm use 22
            npm ci
            export NODE_OPTIONS="--max-old-space-size=2048"
            npm run build
            pm2 start npm --name "alpb-frontend" -- start
            cd ..

            # ── Backend ────────────────────────────────
            cd backend
            npm ci
            pm2 start server.js --name "alpb-backend" --interpreter tsx
            cd ..

            pm2 save

